### ISSUE TITLE
how can I launch the workflow for compiling the PDF 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#16]
I cannot find the way to launch the workflow again. 

I have been able to launch it one time , and get a correct pdf but can find the process with the interface .

on my computer , I cannot compile with ivoatex dependencies . many errors in Make files ...
very frustrating.

**Comment by BaptisteCecconi** [comment]
Go to the [Actions tab](https://github.com/ivoa-std/UCDList/actions), of the repository. Select the last workflow run, which is (at the time of writing): 
https://github.com/ivoa-std/UCDList/actions/runs/793751544

and click on the "Re-run jobs" button (top-right corner)

**Comment by BaptisteCecconi** [comment]
If you just want to get the latest PDF file, you can also go the the [projects tags](
https://github.com/ivoa-std/UCDList/releases), and open the "assets" section, which contains the latest compiled PDF

**Comment by msdemlei** [comment]
On Fri, Apr 30, 2021 at 05:41:11AM -0700, Mireille LOUYS wrote:
> on my computer , I cannot compile with ivoatex dependencies . many
> errors in Make files ...  very frustrating.

What kind of diagnostics do you see?  If you have roughly followed
that ivoatexDoc says and you still see non-trivial error messages,
please file a bug against ivoatex.

**Comment by BaptisteCecconi** [comment]
@loumir did you solve your problems? (in this case we can close this issue)

**Comment by BaptisteCecconi** [comment]
Let me close it for now. We can reopen it if necessary.
