### ISSUE TITLE
unable to push my changes 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#21]
I have tried to add a directory with solar data to test for UCDs . 
I work with command line 
i have cloned ivoa-std/UCDList 
I cannot push my changes  , but git status ask me to do it ...

I find it desperately complex for just a mkdir  to share data between 3 people .

**Comment by msdemlei** [comment]
On Mon, May 03, 2021 at 07:53:15AM -0700, Mireille LOUYS wrote:
> I have tried to add a directory with solar data to test for UCDs . 
> I work with command line 
> i have cloned ivoa-std/UCDList 
> I cannot push my changes  , but git status ask me to do it ...
> 
> I find it desperately complex for just a mkdir  to share data between 3 people .

I suppose you're trying to push to master, right?  That's forbidden
by IVOA policies (which I'm not so hot about either).  You *are*
allowed to push to a branch, though, so:

```
git checkout -b descriptive-name
git push --set-upstream origin
```

should do the trick.

[Full disclosure: I'd have preferred to stay on subversion, too,
where this kind of thing looks a lot simpler; on the other hand, git
*can* do a lot more, so it's worth getting used to it, perhaps
starting with something like
https://devtutorial.io/what-is-git-object-p1141.html]

**Comment by BaptisteCecconi** [comment]
Thanks @msdemlei, I didn't spot the reason why it didn't work. 

However, I have discussed with @loumir offline, and we have decided to proceed a different way. 

Let me close this issue.
