### ISSUE TITLE
comments from Andrea Preite Martinez p3,p14

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#22]
Comments on the text of the Note.

p.3, last line:  log => long

p.14
  8. pos :   ... object on the sky.  Add: or on a celestial body

  9. spect: The end of last sentence is not clear. Change: dependent measures => dependent variables
                 ... and spectral measures spectral lines ...  Erase after  and

Andrea

**Comment by BaptisteCecconi** [comment]
comments included in PR #24
