### ISSUE TITLE
comments from Mark Taylor 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#23]
Section 2:
   "some.log.ucd.x" should read "some.long.ucd.x"

Appendix A.2:
   The bibliography reference to the document 
   "Maintenance of the list of UCD words" is to version 1.20 
   of that document, which describes the previous process of 
   issuing REC track documents.  Shouldn't this be to version 2.0 
   of that document which describes the process using Endorsed Notes?

   (I note that version 2.0 of the document is referenced by URL 
   in the abstract, along with another document referenced by URL; 
   I'm not sure what the policy is for which documents are 
   referenced by URL and which are referenced via the Bibliography).

Appendix E.1:
   It says:
   "Clarified position rules for syntax code E, C, V in Appendix B."
   But I don't see that in Appendix B. Could you mean Section 2?

**Comment by BaptisteCecconi** [comment]
comments included in PR #24
