### ISSUE TITLE
Handling 2 UCD lists : current terms and deprecated terms in a second list

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#35]
As several tools can use the UCDs for automatics processing , like CDS assign/update/validate tools, like 
acidly library from Gregory Mantelet, etc.  I suggest that we also maintain the deprecated terms in a companion list , at each maintenance steps. 
I commit the current version of deprecated terms in this repo.

**Comment by BaptisteCecconi** [comment]
As @msdemlei said in the #36 thread, the format of this file should be included in the UCDList document.

**Comment by loumir** [comment]
The deprecated list is part of the repo now . 
In this iteration there is no term to be deprecated, then no change to this list. When data providers want to update old UCDs in their collection they will find the previous deprecating rules.
