### ISSUE TITLE
pbs with some citations . 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#78]

**Comment by loumir** [comment]
I am stuck due to some citations that are no longer recognized in the pdflatx workflow .

**Comment by BaptisteCecconi** [comment]
This was a syntax error with your `\verbatim` command. This is fixed in the upcoming version.

**Comment by msdemlei** [comment]
On Fri, Jul 15, 2022 at 06:48:55AM -0700, Mireille LOUYS wrote:
> I am stuck due to some citations that are no longer recognized in
> the pdflatx workflow .

Ummm -- which ones?  In the master branch?  I don't see any
trouble...

By the way, in such cases it almost always helps to give the error
message that stumps you (not the whole log).
